### ISSUE TITLE
Customize help message for a command

### ISSUE THREAD

**Issue by RonWang** [tj/commander.js#1023]
Our goal: customize the help message for the root command. 

Existing solution won't help, because we need to append the message on top of auto-gen help, and also modify the auto-gen help a little bit.

Context for our cmd app: below is the root cmd, and we have a `sub-cmd` under the root as well as a `git-style-sub-command`. 

```
commander
    .description('')
    .command('sub-cmd')
    .command('git-style-sub-cmd')
    .version(require('../package.json').version)
    .option('-h, --help', 'output help message', () => {
        console.log('custom help msg');
    })
    .parse(process.argv);
```

In the example I tried using option('-h, --help'), the console.log works for me with my demanded help output. But when I try sub-cmd and git-style-sub-cmd, the help message for the root command is always coming along when I type "cmd sub-cmd --help" and "cmd git-style-sub-cmd --help". 

I noticed #242 , where @shadowspawn  mentioned it won't be supported. Reopen it as it'd be an important feature for us.

**Comment by RonWang** [comment]
lol great post! #1111111111(2)

**Comment by shadowspawn** [comment]
I'll try and explain what is happening with what you tried.

```
    .option('-h, --help', 'output help message', () => {
        console.log('custom help msg');
    })
```

This adds an option which effectively overrides the built-in help since it uses the same flags. The callback is used for  "Custom option processing" and covered in the README.

Flags are treated as "global" and these three calls get processed much the same way and call your action handler:

```
my-command --help
my-command --help sub-cmd
my-command sub-cmd --help
```

This approach would let you customise the help for your main command, but you do miss out on the built-in support for help on the subcommands.

**Comment by shadowspawn** [comment]
Related issue, prefix help with some text: #578

**Comment by madanalogy** [comment]
Hello, just sharing a workaround I found. You can make use of ```.helpOption(flags, description)``` available in v3.0 of commander. Instead of using a string for description, you can call a function that returns a string and have your banner printed in that function (along with any information you want to prefix to the help message).

My implementation:
```
function handleHelp(txt) {
  printHeader();
  return txt;
}
program
  .helpOption('-h, --help', handleHelp('output usage information'));
```

For full implementation including context, see https://github.com/MarkBind/markbind/pull/946

**Comment by shadowspawn** [comment]
@madanalogy 
Won't the header get printed every time you run the command, whether or not you show the help?

**Comment by madanalogy** [comment]
> @madanalogy
> Won't the header get printed every time you run the command, whether or not you show the help?

I did not realise that, thank you for pointing it out! 

I guess this workaround then only works if you always want a banner (e.g. ascii art) to print whenever you run the command, which granted might not be a use case applicable to everyone but was conveniently applicable to the project I was contributing to.

**Comment by shadowspawn** [comment]
Currently there is a single event which is emitted after the help is displayed, `--help`.

A possible approach for allowing more control might be to emit three events:
- `help:header`
- `help:body`
- `help:footer`

If there is a listener for `help:body` then it is called *instead* of the normal help.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

I quite like the `help:header`, `help:body`, `help:footer` idea, and will be keeping an eye on new issues to see if it would be useful.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by DiaxManPl** [comment]
Can anyone give me example usage of `help:body`?

**Comment by shadowspawn** [comment]
The `help:body` pattern did not get implemented. The features that did get added were `.addHelpText()` and `.configureHelp()`, and a Help class for more complex overrides.

**Comment by DiaxManPl** [comment]
Ok. Sorry.
