### ISSUE TITLE
Sub-commands do not work with package.json main

### ISSUE THREAD

**Issue by samherrmann** [tj/commander.js#1044]
Consider the following setup:

lib/index.js
```js
const program = require('commander');
 
program
  .command('update', 'update installed packages', { executableFile: './myUpdateSubCommand' })
  .parse(process.argv);
```

lib/myUpdateSubCommand.js
```js
const program = require('commander');

program.command('foo').action(() => console.log('hello from foo'))
program.parse(process.argv);

if (program.args.length === 0) {
  program.help();
}
```

package.json
```json
{
  "main": "lib/index.js"
}
```

# What works:
```sh
$ node dist/index.js update
Usage: myUpdateSubCommand [options] [command]

Options:
  -h, --help  output usage information

Commands:
  foo
```

# What does not work:
```sh
$ node . update
error: ./myUpdateSubCommand(1) does not exist, try --help
```

# Expected Behavior
It's expected that executing `node . update` yields the same result as executing `node dist/index.js update`.

# Where the problem is:
The path to the sub-command is determined from [argv[1]](https://github.com/tj/commander.js/blob/v3.0.1/index.js#L526), which does not take into consideration the path assigned to the `main` property in `package.json`.

# Version
"commander": "^3.0.1",

**Comment by shadowspawn** [comment]
Yes, for resolving subcommand executables Commander expects `argv[1]` is either the source file, or the installed binary command (i.e. a symbolic link). There is not currently support for coping with a package being passed to node (like when you call `node .`).

The approach I often use is a setup closer to the eventual install. So with a `package.json` like:

```
{
  "name": "my-command",
  "bin": "bin/index.js"
}
```

Instead of `node .` I use:

```
npm link
my-command update
```

(You could work-around the current design in your own code by supplying `argv[1]` yourself. I did a bit of reading and wonder how reliable using `require.main.filename` might be. )

**Comment by shadowspawn** [comment]
Related issue, when calling from Electron app: #512

**Comment by shadowspawn** [comment]
Closing as covered by #512
