### ISSUE TITLE
Any random string (glob) supplied along with version and help flags is treated in the same way

### ISSUE THREAD

**Issue by jamesgeorge007** [tj/commander.js#1064]
[Mevn-CLI](https://github.com/madlabsinc/mevn-cli)
```sh

mevn -h

Usage: mevn <command> [options]

Options:
  -V, --version   output the version number
  -h, --help      output usage information

Commands:
  init <appname>  Bootstraps a basic MEVN stack webapp
  codesplit       Lazy load components as required
  generate        To generate model, route, controller and DB config files
  add             Adds a new plugin on the go
  serve           To serve client/server locally
  dockerize       To launch the webapp within a Docker container locally
  deploy          To deploy the webapp to a cloud solution of choice
  info            Prints debugging information about the local environment
```

```sh
mevn -V

 1.6.1
```

Any random string supplied along, for instance `mevn -Vxyz` or `mevn -hxyz` seems to produce the same output as above.

**Comment by shadowspawn** [comment]
This is actually expected behaviour. Expected in the sense that once you know what is happening, it makes more sense! The version and help option handling short-circuit further processing.

https://github.com/tj/commander.js#options

> Multiple short flags may be combined as a single arg, for example -abc is equivalent to -a -b -c.

So `mevn -Vxyz` is expanded to `mevn -V -x -y -z`. The version flag means the version is displayed and Commander exits without processing the other arguments/options. Likewise, the help flag means the help is displayed and Commander exits.
