### ISSUE TITLE
Typing: In @types/node v13, NodeJS.EventEmitter is no longer a class

### ISSUE THREAD

**Issue by be5invis** [tj/commander.js#1151]
Source: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40927

> * BREAKING: Replaced global EventEmitter class with interface as it's purely virtual and only there for global declarations.
>   * This required various updates in other package since they sometimes used extends EventEmitter or extends NodeJS.EventEmitter.

**Comment by shadowspawn** [comment]
Thanks for report.

Independently, I recently wrote a PR to remove the EventEmitter from our TypeScript to try in Commander 5.x but was not planning for that in 4.x:  #1146

I'm not sure what we'll do for 4.x. That PR for DefinitelyTyped is across a LOT of files so that fix is widely applied and will look into that.

**Comment by shadowspawn** [comment]
I think Commander may not not affected by this change, as Command is declared as an interface not a class:

https://github.com/tj/commander.js/blob/f31d757315a5ad2ef17815de7c46b98418f3051d/typings/index.d.ts#L28

I tried updating to latest `@types/node@13` and was not able to reproduce any problems. Are you seeing issues?

**Comment by be5invis** [comment]
@shadowspawn 
I tried to update Commander and it seems working now. Maybe I was using old version that caused this? Closed.

**Comment by shadowspawn** [comment]
Old version... Digging...  #1081

For future readers, this issue is fixed in Commander v4.
