### ISSUE TITLE
Problems between chained calls

### ISSUE THREAD

**Issue by WUSO01** [tj/commander.js#1209]
**app.js**:
```javascript
#!/usr/bin/env node

const program = require('commander')

program
  .command('init <name>')
  .action(name => {
    console.log(name)
  })
program.parse(process.argv)

```
run `node app.js init myapp`, will print "myapp", but while I use Chained syntax:

```javascript
// ...
program
  .command('init <name>')
  .action(name => {
    console.log(name)
  })
  .parse(process.argv)
```
nothing printed.

**Comment by shadowspawn** [comment]
The `.command` call is returning a new command to configure. The `.parse` is processed by the command you call it on, which in the second case is the "init" command rather than the program. Effectively your second case is like:

```
const initCommand = program.command('init <name>')
  .action(name => {
    console.log(name)
  });

initCommand.parse(process.argv);
```

I still see some output, although not what you intended:

```
$ node app.js init myApp
init
```

The help is from the "init" command:

```
$ node app.js --help
Usage:  init [options] <name>

Options:
  -h, --help  display help for command
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
