### ISSUE TITLE
5.0.0: `--help` call stopped all tests

### ISSUE THREAD

**Issue by sanex3339** [tj/commander.js#1218]
After upgrade from 4.1.1 on 5.0.0 `--help` call stopped all tests. Tests are not failed but just stopped.

The bug here in the `master` branch
https://github.com/javascript-obfuscator/javascript-obfuscator

Just `yarn`, then `yarn run test`, only few tests will run, and after `--help option is set` all next tests will be cancelled.

`help` usage:
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/cli/JavaScriptObfuscatorCLI.ts#L361

Test:
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/test/functional-tests/cli/JavaScriptObfuscatorCLI.spec.ts#L723

**Comment by shadowspawn** [comment]
I have worked out the area of behaviour that has changed, but in between EventEmitter (Commander) and Sinon (your code) I can't give you a detailed explanation of how the tests stop.

You have code which calls:
- configureCommands
    - add options
    - call `.parse`
- configureHelp
    - add `.on('--help')`

In general `.parse` should be called only after adding the `--help` listener, but apparently in Commander v4 you could get away with adding the listener afterwards in some cases. The command parsing used to defer some processing through the event emitter, but in Commander v5 now does more of it directly.

In particular, when I call
```
node bin/javascript-obfuscator test/fixtures/sample --help
```

With Commander v4: configureHelp is called, and the custom help is added on the end of the displayed help.
With Commander v5. configureHelp is not called as the program exits after displaying the default help as soon as `.parse` is called.

I think if you refactor your code slightly to call `.parse` only after adding the help listener, you will get consistent behaviour:

- configureCommands
    - add options
- configureHelp
    - add `.on('--help')`
- call `.parse`

**Comment by sanex3339** [comment]
Thank you, i will try

**Comment by sanex3339** [comment]
The same problem if i call `parse` after `.on('--help')`

**Comment by shadowspawn** [comment]
Ok, I think that change will still be needed to get correct behaviour, but it isn't the cause of the test stopping. More digging...

Ah ha! Tricky!

1) There is a bug in Commander v4 that help flags after an argument are not detected and the help is not displayed.

```
node index.js --help # help is displayed
node index.js --help arg # help is displayed
node index.js arg --help # help flag is not detected, help is not displayed
```

Your program has what might be a work-around for the bug by looking for the help flags itself in `run`:

```js
const canShowHelp: boolean = !this.arguments.length || this.arguments.includes('--help');
if (canShowHelp) {
  this.commands.outputHelp();
  return;
}
```

2) The breaking test is parsing `node bin/javascript-obfuscator test/fixtures/sample --help` and is encountering a difference in behaviour.

In Commander v4, Commander misses the help flag and your `run` code calls `outputHelp()`.
In Commander v5, Commander detects the help flag and calls`.help()`.

3) A difference between calling `.help()` and `.outputHelp()` is that `.help()` calls `process.exit`. That is what is breaking your test!

One approach to handling exit in unit tests is to add `.exitOverride()` to convert the exit to a throw and catch the error. This require modifying the program you are testing, so is not always convenient.

Another approach is to simply stub `process.exit`. There isn't always a complete solution since if you let the code carry on other code may also run (#1216), but for your case this is likely to be fine. 

The unit tests in Commander v2 used the stub approach to handle the exit in various tests, for example: https://github.com/tj/commander.js/blob/v2.20.3/test/test.command.allowUnknownOption.js

**Comment by shadowspawn** [comment]
After working out the details of behaviour, I can see that calling `parse` before adding the help listener does affects Commander v4 too. This call will not add your custom help on the end:

```
node bin/javascript-obfuscator --help
```

**Comment by sanex3339** [comment]
Thank you for the good explanation. WIll stub `process.exit`
