### ISSUE TITLE
Getting arguments without defaults

### ISSUE THREAD

**Issue by jakobrosenberg** [tj/commander.js#1261]
Is this possible?

I'm working on a project where config values are read from a default config, user config and CLI.

I would like to do something along the lines of
```javascript
const config = {...defaultConfig, ...userConfig, ...commanderOptions}
```

But this is not possible as Commander outputs all config values, effectively overwriting the user config.

**Comment by shadowspawn** [comment]
A couple of different approaches:

1) Make the default smarter. You could include the other config sources in the calculation of the default value you give to Commander.

2) Remove the defaults. You could not explicitly set defaults in Commander, and combine the config sources afterwards. (You might include the defaults in the description of the option, rather than as a true default, so user still knows what is going to happen.)

If you are combining config source afterwards, note that the old behaviour of `.opts()` was to explicitly include all options whether or not they had a value. The new behaviour if you turn off storing options as properties is that only the options with values are included in `.opts()`. See `.storeOptionsAsProperties(false)`.

**Comment by jakobrosenberg** [comment]
I've considered no 1. but I'm concerned it could be misleading and potentially harmful if a user confuses their own config values with the project/ecosystem defaults. On the other hand, I guess the risk of false expectation goes both ways, since users would expect the listed default values to be the effective values.

I'll deliberate on your input and see where it takes me. Thanks for your help @shadowspawn.
