### ISSUE TITLE
 The callback function of fs.readFile does not execute

### ISSUE THREAD

**Issue by Ronaldo-C** [tj/commander.js#1280]
when i specify a command,the callback function of fs.readFile does not execute.
versions: `5.1.0`
```
const { program }  = require('commander');
const homedir = require('os').homedir()
const fs = require('fs')

program
  .command('add')
  .description('add a task')
  .action((args) => {
    
  });

  console.log('start')
  fs.readFile(homedir, { flag: 'a+' }, (error, data) => {
    console.log('callback fun')
  })

program.parse(process.argv);
```

**Comment by shadowspawn** [comment]
What did you type on the command line? Assuming you supplied no arguments:

1) `readFile` starts an asynchronous task,
2) `program.parse` displays the help because no command was specified, AND...
3) calls `process.exit` (before `readFile` has a chance to call the callback)

e.g.

```shell
$ node index.js    
start
Usage: index [options] [command]

Options:
  -h, --help      display help for command

Commands:
  add             add a task
  help [command]  display help for command
```

**Comment by Ronaldo-C** [comment]
Yes, when I switch to version `4.1.1`, there is no such problem

**Comment by shadowspawn** [comment]
Version 4 did not display the help under those circumstances, it silently did nothing. You will see same issue with callback not finishing in version 4 if you specify `--help`.

Two suggestions, depending on how you want your "real" program to behave:

1) Test for no arguments before calling `.parse`, and handle it yourself or just ignore it.

2) Specify `exitOverride()`so Commander will `throw` rather than `exit`, and you can catch the error and allow the asynchronous tasks to finish.

**Comment by Ronaldo-C** [comment]
Okay thank you
