### ISSUE TITLE
Can not test commands using jest

### ISSUE THREAD

**Issue by lucasgmagalhaes** [tj/commander.js#1329]
I made a cli but I facing some problems when testing. Commander.parser always fail and I cant figure out what I'm doing wrong.

The test:
![image](https://user-images.githubusercontent.com/19666463/90081783-a65d2d80-dce4-11ea-9444-3e165cbdb5e3.png)

![image](https://user-images.githubusercontent.com/19666463/90081971-048a1080-dce5-11ea-936e-e65403b5d7ce.png)

The repo: https://github.com/lucasgmagalhaes/corde/tree/commander-help

It can be executed using: **yarn test ./tests/cli/cli.test.ts**

**Comment by shadowspawn** [comment]
The handling of `--version` calls `process.exit()` rather than returning. You can use `.exitOverride()` to throw instead after displaying the version, and catch that.

You can have a look at Commander's own tests to see some possible patterns to use:
https://github.com/tj/commander.js/blob/master/tests/options.version.test.js

**Comment by lucasgmagalhaes** [comment]
Thank you so much! Sorry for the inconveniance.
