### ISSUE TITLE
Commander exits with code 1 if no command provided or not --help

### ISSUE THREAD

**Issue by karazy** [tj/commander.js#1442]
Since I upgraded to commander 7.0 I get an exit code of 1 when just calling my cli program without specifying any arguments.

Here is a barebone app to replicate this behaviour:
**cerr.js**
```
#!/usr/bin/env node
const commander = require('commander');


//Entrypoint
(() => {
    const program = new commander.Command();
    program.command('test', 'Test command.').alias('t')

    program.parse(process.argv);
})();
```

**package.json**
```
{
  "name": "commander-error",
  "version": "1.0.0",
  "description": "",
  "main": "cerr.js",
  "bin": {
    "cerr": "./cerr.js"
  },
  "scripts": {
    "start": "node cerr.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "commander": "^7.0.0"
  }
}

```

Call it in shell.
```
 ~ cerr; echo $?
Usage: cerr [options] [command]

Options:
  -h, --help      display help for command

Commands:
  test|t          Test command.
  help [command]  display help for command
1

➜  ~ cerr --help; echo $?
Usage: cerr [options] [command]

Options:
  -h, --help      display help for command

Commands:
  test|t          Test command.
  help [command]  display help for command
0
```

So if I use --help I get code 0. If not I get 1.

Expected behaviour would be to see the help and have an exit code of 0.

**Comment by shadowspawn** [comment]
Thanks for the example code and usage.

This is by design. Although it is also a convenient shortcut to the help, Commander treats it as a possible error for "no command specified" and shows the help. This can pick up mistakes in scripts, while not usually noticeable for interactive use.

If you intend to display the help and the exit code matters, then you can display the help with `cerr --help` (as you noted) or `cerr help`.

You can see the same behaviour with displaying help and exit code if you run `git` or `npm` with no arguments.

**Comment by karazy** [comment]
Thanks a lot for the explanation. Makes sense.
After the upgrade some of my tests where failing but I'll already added `--help` and they work again.
Keep up the great work.
