### ISSUE TITLE
Support event listener for option fallback to default value

### ISSUE THREAD

**Issue by Kerruba** [tj/commander.js#1457]
Hello,

I would like to set a global variable based on the value associated with an option. But right now there's no support for the default value of an option. My plan was to do something like this
```
let program = new commander.Command();
program.option('-t, --test <value>', 'a test option', 'my-default')
program.on('option:test', function(value) => {
   process.env.MY_ENV_VAR = value 
})
```

but this only works if the option is passed, not if the default value is used.

A possible workaround right now would be to set the env variable outside of the program and override it only if the option is passed, but check this other issue instead https://github.com/tj/commander.js/issues/1456

**Comment by shadowspawn** [comment]
Another approach is to set the environment variable after the parsing when the option has the final value, so for example at the start of the action handler. 

Your work-around of setting the environment variable before parsing would mean less repeated code for doing this with a global option.

**Comment by shadowspawn** [comment]
There is some overlap with #1197, from the point of view of a hook after the options are parsed but before the action is run.

**Comment by shadowspawn** [comment]
I am not planning to emit events when falls back to default value. Some work-arounds discussed. No further activity in a month. Closing.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by chriscalo** [comment]
I have a need for something similar. I'm trying to find a way of setting environment variables _inside_ the commander script and the suggested workaround doesn't seem to address the need.

> Another approach is to set the environment variable after the parsing when the option has the final value, so for example at the start of the action handler.

The problem with this is that I need to set environment variables **before** any action is run. As I understand it, as soon as you call `program.parse()`, command actions get called, making it too late to set environment vars.

I basically want to do something like the following:

``` sh
my-script --env=prod cmd foo
# OR
my-script cmd foo # defaults to --env=dev
```

and have some function called before any actions are called to handle the value of the `--env` option.

I don't care too much what the solution is, but I've looked deeply over the docs and searched for other answers and can't find any way of doing what I'm looking for.

One fix is what this bug describes, that a default value for `--env` will also trigger the `option:env` event. Then I could do something like the following, though this doesn't work today:

``` js
#!/usr/bin/env node
const { Command } = require("commander");

const program = new Command();

program
  .option("-e, --env <name>", "set env vars from <name>.env file", "dev")
  .on("option:env", function (name) {
    // I want to set env vars here
    // unfortunately, this doesn't get called for the default value
    // how do I force this function to always get called?
  });

program
  .command("foo")
  .action(function () {
    // env vars need to always be set by the time this function gets called
  });

program.parse();
```

Alternatively I made an attempt at calling `program.parse()` and then setting environment vars, but then I don't know how to trigger command actions at that point because it's not covered in the docs:

``` js
#!/usr/bin/env node
const { Command } = require("commander");

const program = new Command();

program.option("-e, --env <name>", "set env vars from <name>.env file", "dev")

// declare the command, but don't attach an action because env vars need to be set
program.command("foo");

program.parse();
const { env } = program.opts();

// now we can set env vars every time whether the value was passed or the default was used
setEnv(env);

// but now I have a new problem: how do I execute the logic for routing `program.args`
// to specific actions to handle them? this isn't covered in the docs
```

What I'm looking for:
1. use `commander.js`'s parsing logic to parse options
2. run some function every time, after parsing, but before any action
3. execute the right action for the program args

Is there any way to do this today?

If not, would it be possible to reopen this issue?

**Comment by shadowspawn** [comment]
A quick answer. There is not direct support for this. I still don't see emitting an event for the right pattern (although I appreciate you can see how to achieve what you want with it). As mentioned earlier, the open issue about adding hooks is #1197.

A possible approach is to process the default first before processing the options. Like:

```js
readEnv("dev");

program
  .option("-e, --env <name>", "set env vars from <name>.env file")
  .on("option:env", function (name) {
    readEnv(name);
  });
```

Thanks for the explanation and examples. Feel free to open a new issue with what you covered and the problem if #1197 does not cover what you have in mind well enough.

**Comment by chriscalo** [comment]
Thanks for the quick response 👍

Unfortunately, the workaround you propose won't work in my situation because loading the default environment may set variables that need to be unset when loading a different environment.

What I don't understand from in #1197 is exactly what the suggested fix is. This almost sounds like setting pre- and post-run handlers _for each command_, which isn't what I'm looking for. Unless, perhaps it's also proposing a post-option handler that can run _every time_ whether the option was set or its default value was used.

> How about option to add a preRun and a postRun function to each command to run before or after the main function?

For my situation I need the ability for some function to run:

1. Every time
2. After args parsing
3. Before command actions

Having looked through all of the related issues, it seems commander.js has a strong perspective on not allowing some function to be called in all situations, which is exactly what I and many others seem to need. It seems that providing any means of having a function be called _every time_ will solve several of these issues.

Some examples:
- you can set an `option:foo` event handler which will be called when `--foo` is explicitly set, but not when its default value is used
- you can set a `command:*` event handler which will be called whenever a matching command was not found, but it won't run for all commands as the `*` suggests

**Comment by chriscalo** [comment]
I was able to think of another work-around that splits the logic into two `Command` instances:
1. a `Command` instance just for parsing global options
2. run logic to react to global options
3. another `Command` instance for running `command()` `action()`s

``` js
#!/usr/bin/env node

// first, parse just the options we need to act on…
const envOptionParser = new Command();
envOptionParser.option("--env <env>", "set environment", "dev");
envOptionParser.parse();
const { env } = program.opts();
setEnv(env);

// then real program follows…
const { Command } = require("commander");
const program = new Command();
program.option("-e, --env <name>", "set environment", "dev")
program
  .command("foo")
  .action(function () {
    // env vars will always be set at this point
  });
program.parse();
```

I'll try this out to see if it works. If so, my need is satisfied, though I'm left with a feeling that accomplishing this shouldn't require so many contortions. 🤔

**Comment by chriscalo** [comment]
This approach indeed works for my situation.

With this I'm able to work around the issue, but it still feels wrong. It would be really great if commander.js had a built-in solution to handle this and similar situations.

Thanks for giving this some thought!

**Comment by shadowspawn** [comment]
Replying to https://github.com/tj/commander.js/issues/1457#issuecomment-828407788

> Knowing all of this, do you recommended opening a new issue or just following #1197?

I recommend follow #1197

> What I don't understand from #1197 is exactly what the suggested fix is.

There isn't a concrete suggested fix yet, but I am forming some ideas.

The original post was a little unclear on whether "pre run" and "post run" were individual to the command, or more global and applying to subcommands too. For `.addHelpText()` we added `before`/`after` and `beforeAll`/`afterAll` to explicitly offer both variations. In fact for adding run hooks/handlers I think the "all" is the more powerful and useful variation, but would probably offer both again.

So say, the `beforeAll` run handler could match your request for:

>1. Every time, no matter what the input is
>2. After args parsing
>3. Before command actions
