### ISSUE TITLE
Command abbreviation support

### ISSUE THREAD

**Issue by glensc** [tj/commander.js#1463]
Coming from php background, symfony/console allows to abbreviate commands to lessen typing:

```
➔ ./bin/console.ts --help
Usage: console [options] [command]

Options:
  -h, --help      display help for command

Commands:
  sync <worker>   Run sync for worker
  help [command]  display help for command
```

it should be able to find 'sync' command, as it's unique enough:

```
➔ ./bin/console.ts s
error: unknown command 's'. See 'console --help'.
```

**Comment by shadowspawn** [comment]
I got used to this with Mercurial, but not supported by Git and I am out of the habit now. With options, [getopt_long](https://manpages.debian.org/stretch/manpages-dev/getopt_long.3.en.html#getopt_long()_and_getopt_long_only()) supports unambiguous abbreviations.

**Comment by glensc** [comment]
@shadowspawn implementing this on your own is very trivial:
1. iterate over all command names and aliases
2. push substring(0, length(argument_from_commandline)) to candidates array
3. return candidates[0] if candidates.length === 1
4. return null otherwise

additionally, the commander could do:
1. if a non-unique match was found print names that were found
2. if nothing was found, print out all command names suggestion

**Comment by shadowspawn** [comment]
I think step 2 is incomplete, but I get the intent. 

However, the hard part for me is not implementing it, but deciding whether it is appropriate as the behaviour for all users of the library and all ways Commander could have been used.

**Comment by glensc** [comment]
corrected logic, added as a step under "1".

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

My main reservation about using abbreviation support with a program is that it can make adding a command a breaking change. Users who have used a previously unambiguous abbreviation in a script will get an error if the new command is also a candidate.

On a related note, I am open to offering an unambiguous match as a candidate for unknown commands. See #1590

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
