### ISSUE TITLE
Option takes place of missing, required value

### ISSUE THREAD

**Issue by codekie** [tj/commander.js#1484]
I really like this library and it already has saved me a lot of time, implementing CLIs. Thanks for your great work! However, today I have noticed that if the required value of an option has been omitted, the subsequent option takes its place.

If the configuration

```
program
    .option('--tag <version>', 'Tags the release with `version`', 'latest')
    .option('--dry-run', 'Shows which commands would be run, without actually deploying', false)
    .parse();
```

is called with following options:

```
$ deploy --tag --dry-run
```

then the parsed options look like this:

```
{ tag: '--dry-run', dryRun: false }
```

The parser does not throw an error that the value for `--tag` is missing and it also takes the following option as value and "swallows" the consumed option.

My expectation would be that commander recognizes defined options (short and long), rejects them as values and instead throws a "missing argument"-error. If it is necessary to accept values, which resemble options, they should be passed within quotes.

**Comment by shadowspawn** [comment]
Glad you are liking Commander. 😄 

This is a "feature" rather than a "bug". An option taking a required value will consume the following argument whether or not it starts with a `-`. An option taking an optional value will only consume the following argument if it does not start with a `-`. 

For interest, actually adding quotes is not enough to change how an argument should be parsed. The quotes get removed by the shell before they even reach your program. 

```
% node -e "console.log(process.argv)" foo "bar" 'hello'
[ '/usr/local/bin/node', 'foo', 'bar', 'hello' ]
```

Instead, the work-around for a leading `-` for optional option-values is to include the option value in the same argument as the option, like `--temperature=-5` or `-t-5`.

The upside of the Commander behaviour is it is easy to pass option values that start with `-`, whether a number or something else. e.g.

```
start-weather-station --freezing-point -5
```

The downside is that when you omit a required option value then the parsing may not fail. As you encountered!

**Comment by codekie** [comment]
I see. Thanks for the clarification.
