### ISSUE TITLE
How to parse ./program command -- foo?

### ISSUE THREAD

**Issue by seb-mtl** [tj/commander.js#1485]
I am using `commander` for my [command-line application](https://github.com/snowtrack/snowfs) and I try to find a solution to replicate the following command:

```
git checkout -- file.psd
```

Since `--` has already a special meaning, does anyone know what workaround I could use? I was looking into custom option handling but since `--` is so special. Any help is highly appreciated!

**Comment by shadowspawn** [comment]
Commander consumes the `--` and stops looking for options when it is encountered.

If you want to try for that exact syntax, you could look at the raw arguments to detect the `--`.

Some other ideas: you could use a different magic symbol to change the interpretation, or separate out the two modes of operation by using differently named commands, or use an option to control the mode. e.g.

```
my-util checkout @ file.psd
my-util checkout branch
# or
my-util checkout branch
my-util checkout-pathspec file.psd
# or 
my-util checkout branch
my-util checkout --pathspec file.psd
```

**Comment by seb-mtl** [comment]
Thank you for your input! 

> If you want to try for that exact syntax, you could look at the raw arguments to detect the --.

Could you elaborate on that idea?

**Comment by shadowspawn** [comment]
I was thinking try something simple to see if likely to work for you. Instead of testing first command-argument after parsing to see if it is `--`, instead test to see if `process.args` contains an argument matching `--`. 

For interest, you can use one `--` for Commander and another one to appear in the command-arguments after parsing, but I assume you don't want to expose this syntax!

```
my-util checkout -- -- file.psd
```

**Comment by seb-mtl** [comment]
Thanks a lot for the clarification and your help!
