### ISSUE TITLE
Parsing arguments after displaying help breaks printing Usage to console

### ISSUE THREAD

**Issue by kud** [tj/commander.js#150]
Hey,

I'm using your great package (https://github.com/kud/happy-plan/blob/master/bin/happyplan) but I have a question.

Why do I have "undefined" when I type my command?

```
happyplan

  Usage: undefined [options] [command]

  Commands:

    * [options]
    dev                    development mode
    dist                   distributing mode
    newpost                create a new post
    init                   initialize
    publish                publish on github

  Options:

    -h, --help  output usage information
```

**Comment by shadowspawn** [comment]
Thanks for explanation @alexmingoia 

This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
