### ISSUE TITLE
command global option fails when sub command registered

### ISSUE THREAD

**Issue by RobertWu-TIBCO** [tj/commander.js#1554]
## I clone the master branch and edit the example `options-defaults.js` to append a sub command  `.command("sub", "subcommand");`, then I see it fails as pictured:

![commander_options_fail_with_sub_command](https://user-images.githubusercontent.com/20295019/123942957-36c06180-d9ce-11eb-8e7e-2a110008d39e.PNG)

## Here is the code after changes:
```
program
  .option("-c, --cheese <type>", "Add the specified type of cheese", "blue")
  .command("sub", "subcommand");
```

## Here is how I compare the code for changes:

![commander_options_fail_with_subcommand_bcompare](https://user-images.githubusercontent.com/20295019/123943408-b51d0380-d9ce-11eb-9f32-e9fc2f24d44c.PNG)

**Comment by shadowspawn** [comment]
In a simple program with no subcommands it is quite normal to put the code which uses the options after calling `.parse()`. Once you add subcommands, Commander does not fall through silently if it might be a user mistake on the command line.

In your example, Commander assumes you have forgotten to specify the subcommand and shows the help rather than silently do nothing. (Same thing would happen if you did not specify the global option on the command line.)

If you add an action handler to the program, Commander can see the top level command is implemented and will call that.

e.g.
```
program
  .option("-c, --cheese <type>", "Add the specified type of cheese", "blue")
  .action(() => {
    console.log('called main command')
  });
```

**Comment by RobertWu-TIBCO** [comment]
Great Thanks ! Once add `action` part , the issue fixed.

**Comment by RobertWu-TIBCO** [comment]
So I could handle any options after `program.parse()` then.
