### ISSUE TITLE
Can I use commanderjs in browser?

### ISSUE THREAD

**Issue by chkaos** [tj/commander.js#1563]
Hi there.
I plan to devlop a web-based terimal that communicate with server via websockets. Can I use commanderjs just for args handling and command verification only, maybe plus autocompelte?

If not, can you recommend some other libarys that can fit my needs?

**Comment by shadowspawn** [comment]
You can call `.parse()` just for verification, but if you have subcommands then you'll probably want to have something in the action handler to capture what command was called with the parsed options and command-arguments.  Commander is not set up to parse the arguments and inspect the result afterwards.

There is not direct support for auto-complete.

There are some frameworks which are aimed at implementing a custom "terminal" rather than running a single command. An older one I see mentioned is https://github.com/dthree/vorpal

**Comment by shadowspawn** [comment]
Ok, answering your "in browser" question this time!

Commander is written as a node application, so probably not what you are looking for.

**Comment by chkaos** [comment]
Thanks for your quick response！
