### ISSUE TITLE
Add a quick start section in README

### ISSUE THREAD

**Issue by ayoubmehd** [tj/commander.js#1588]
For new Users the current README way is confusing.
it should be a quick start section that explains the basic usage.

**Comment by shadowspawn** [comment]
Do the examples help as a quick introduction?

https://github.com/tj/commander.js#examples

(I reworked the examples and had intended to link to them from the top of the document as a quick idea of what using Commander was like, but didn't add the link.)

**Comment by ayoubmehd** [comment]
@shadowspawn Yes, that's Good

**Comment by Amoghtech** [comment]
Can i take this issue?

**Comment by shadowspawn** [comment]
Short version: yes.


Long version

Thanks for asking and offering.

I am interested in improving onboarding for a new user, and it is years since I was one.

(I may make changes or do something different in the end, as I have rewritten much of the README in the last couple of years and mostly in "my" style now.)

**Comment by ayoubmehd** [comment]
÷ I opened a pull request #1591

**Comment by shadowspawn** [comment]
I was inspired to have another go at this today: #1665

**Comment by shadowspawn** [comment]
Commander v9 has been released.
