### ISSUE TITLE
Does not work on node 12

### ISSUE THREAD

**Issue by paladox** [tj/commander.js#1603]
We're using the node package from debian which is 12.22.5 and also npm which is 7.5.2.

We cannot get the commands to work... I've tried the demo where I could reproduce (e.g. https://github.com/tj/commander.js/blob/master/examples/defaults)

Returns

```
root@mw8:/srv/mathoid/commander.js# examples/defaults
  - undefined template engine
  - undefined cheese
  - undefined
```

**Comment by shadowspawn** [comment]
Oh, that example is out of date. But convenient to show the problem!

Option values used to be stored on the command. The new default, since Commander v7.0, is to store them separately. The option values can be accessed with `.opts()` whichever way they are stored. The relevant setting is `storeOptionsAsProperties()`.

See the migration tips in the v7.0.0 release notes: https://github.com/tj/commander.js/releases/tag/v7.0.0

**Comment by paladox** [comment]
Aha! Thanks!. I see there's storeOptionsAsProperties which fixed it!
