### ISSUE TITLE
tslint error

### ISSUE THREAD

**Issue by zizxzy** [tj/commander.js#1634]
When I use the tslint to check the synatx when I commit the code, I will report an error when getting commander.args.length in the tslint/lib/tslintlib file.
```
git commit -m "feat:...."

```
// error
/node_modules/tslint/lib/tslintCli.js:178
  commander.args.length > 0)) {
                 ^
TypeError: Cannot read property 'length' of undefined
  at Object.<anonymous> (/Users/bytedance/Desktop/sdk/bitable-sdk/node_modules/tslint/lib/tslintCli.js:178:20)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (internal/modules/cjs/loader.js:928:32)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at Object.<anonymous> (/Users/bytedance/Desktop/sdk/bitable-sdk/node_modules/tslint/bin/tslint:3:1)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
husky > pre-commit hook failed (add --no-verify to bypass)
```

```js
//tslint/lib/tslintlib
var parsed = commander.parseOptions(process.argv.slice(2));// The returned object has no args attribute
commander.args = parsed.args;
if (parsed.unknown.length !== 0) {
    commander.parseArgs([], parsed.unknown);
}
var argv = commander.opts();
console.log(process.argv.slice(2));
if (!(argv.init ||
    argv.test !== undefined ||
    argv.project !== undefined ||
    commander.args.length > 0)) {
    console.error("No files specified. Use --project to lint a project folder.");
    process.exit(1);
}
```

```js
// commands/typings/index.d.ts/
 parseOptions(argv: string[]): commander.ParseOptionsResult;
```

```js
// the interface has no args attribute
  interface ParseOptionsResult {
    operands: string[];
    unknown: string[];
  }
```
So how do I resolve this error?

**Comment by shadowspawn** [comment]
The usual way to use Commander is to call `.parse()`. See the examples in the README and example files. `.parse()` sets the `args` property on the command.

If you do want to use the low-level `.parseOptions()` directly, it returns two arrays which are the `operands` (arguments with known option and option values removed) and `unknown` arguments. The unknown are the arguments which could not be processed, usually because the parsing hit an unknown option perhaps for a subcommand.

To turn `ParseOptionsResult` back into an array of the remaining arguments you can concatenate them together.

```
var parsed = commander.parseOptions(process.argv.slice(2));
const args = parsed.operands.concat(parsed.unknown);
```

You can see code like this within Commander:

https://github.com/tj/commander.js/blob/43f4743864e2f670db5eebcf88c92aa4612c54f1/lib/command.js#L1190

**Comment by zizxzy** [comment]
thanks @shadowspawn 
Later I used the command '_yarn add tslint@6.1.3_' to change the version of tsLint and the problem was resolved.

**Comment by shadowspawn** [comment]
Original problem solved, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
