### ISSUE TITLE
Missing values for required options wrongly get value of next option name

### ISSUE THREAD

**Issue by peiyangyu** [tj/commander.js#1684]
``` 
calRTT [options]

       --times <num>        "Times desc"
       --verbose            "if verbose"
```
For example, my CLI name is calRTT and it has two arguments, `times` and `verbose`. If I run this program in terminal and input as
`calRTT --times --verbose`, it will return string "--verbose" if I call `options.times`. But what I want is to throw an exception as it missed value **num**, instead of return the name of next option name with quotes. How can I solve this?

currently my code is:
```
const program = new Command()
program
.name("calRTT")
.option('-t, --times', 'Times desc')
.option('-v, --verbose' 'if verbose')

program.parse(process.argv)
const options = program.opts()
```

**Comment by shadowspawn** [comment]
This is expected behaviour. Options taking a required argument take the next argument even if it starts with a dash. (Options taking an optional argument don't do this and you could check yourself, but the help would be misleading.)

The best approach might be to add a custom parser since it looks like you are expecting a number. Then you can throw an error if you don't get a number, and it covers this particular case and more. See `myParseInt` in the README.

```js
program
  .option('-t, --times <num>', 'Times desc', myParseInt)
```
