### ISSUE TITLE
Option string is being sanitized in an unexpected way

### ISSUE THREAD

**Issue by jacoblockett** [tj/commander.js#1695]
I'm trying to receive input from a user in an option that will allow me to extract specific templated text. If the option flag is "-a", here's what happens:

-a "here is a ${template} string" produces "here is a   string"
-a 'here is a ${template} string' produces "here is a ${template} string"

I've looked over the docs but may have missed something. Is this being done for a reason? Here's some stuff that might help:

Commander version: 9.0.0
Nodejs version: 17.5.0
Sample code to reproduce the issue:
```js
const { Command } = require("commander")

const program = new Command()

program
	.command("test")
	.option("-a <template>")
	.action(options => {
		// TEST1 with double quotes: node app.js test -a "sample ${template} string"
		// TEST2 with single quotes: node app.js test -a 'sample ${template} string'
		console.log(options.a)
		// TEST1: options.a == "sample  string"
		// TEST2: options.a == "sample ${template} string"
	})

program.parse()
```

**Comment by shadowspawn** [comment]
Thanks for the detail and example code.

The issue is happening at the shell, before node, before Commander. You can see this by checking what is in `process.argv` in your program, or simply using `echo` to get an idea of what is happening:

You are using the same characters the shell uses for variable substitution, and the double speech marks do not prevent the shell from doing the substitution.


```
% echo "here is a ${template} string" 
here is a  string
% echo 'here is a ${template} string'
here is a ${template} string
% export template=surprise   
% echo "here is a ${template} string" 
here is a surprise string
```

**Comment by jacoblockett** [comment]
Aha, silly me. I _would_ try to do something that breaks at the shell level lol. Thanks for the speedy response!
