### ISSUE TITLE
Help: unexpected output for default option value when using plain backslashes

### ISSUE THREAD

**Issue by cedx** [tj/commander.js#1738]
I have a command that uses a default option value set to a Windows path: backslashes are escaped with backslashes (i.e. `"C:\\Path\\To\\Folder"`).

When I use the `help` command, the path is printed with the double-backslashes instead of the expected single ones:

```js
// File "main.js"
import {program} from "commander";
program.name("Sample")
  .option("-p <path>", "the path", "C:\\MyFolder")
  .parse();
```

```shell
# Current output:
$ node main.js --help
Usage: Sample [options]

Options:
  -p <path>   the path (default: "C:\\MyFolder")
  -h, --help  display help for comman

# Expected output:
$ node main.js --help
Usage: Sample [options]

Options:
  -p <path>   the path (default: "C:\MyFolder")
  -h, --help  display help for comman
```

Commander v9.3.0, Node.js v18.2.0

**Comment by shadowspawn** [comment]
This is an implementation quirk due to the code using `JSON.stringify()` to prepare the default for display.

This got looked into for somewhat related reasons in #1283. Attempting to improve the display of certain defaults seemed as likely to break other cases. Instead, there is now a way to specify the string to use in the help. 

So if it annoys you enough, you can work-around the issue by using `Option.default(value, description)`.

**Comment by cedx** [comment]
OK, thanks for the suggestion.

```js
// File "main.js"
import {program, Option} from "commander";

const defaultPath = "C:\\MyFolder";
program.name("Sample")
  .addOption(new Option("-p <path>", "the path").default(defaultPath, `"${defaultPath}"`))
  .parse();
```
