### ISSUE TITLE
options Undefined

### ISSUE THREAD

**Issue by arnaud422** [tj/commander.js#1820]
Hello, could someone tell me why the all option is always undefined? (even with options.all)
![option-undefinedPNG](https://user-images.githubusercontent.com/48210106/201750401-0745c24a-42e5-4a93-9c2b-8b84156ca00e.PNG)

**Comment by shadowspawn** [comment]
1) What are you typing on the command-line to call the program?

2) Are you calling `program.parseAsync()`? (You need to call one of the two parse routines, and since you have an async action handler it should be `parseAsync`.)

3) If you copy and paste your program into a code block in the issue comment, it is more useful for searches and for reproducing the problem than a picture. Code blocks in markdown have three back-ticks before and after. You can optionally put the code language after the back-ticks, with `js` being a code for JavaScript. Like this:

````
```js
code goes here
```
````

**Comment by arnaud422** [comment]
Thank you for your quick response! I do use "npm start" for testing. So I'll change that. Yes I made a capture without thinking about the three  back-ticks ;-)

**Comment by shadowspawn** [comment]
You can use `npm run`, but need to stop npm from eating your options. See #1761 for more.

**Comment by arnaud422** [comment]
great thanks
