### ISSUE TITLE
[Bug] Error contains undecoded HTML entities

### ISSUE THREAD

**Issue by KaKi87** [tj/commander.js#1845]
Hello,

I created a `command` with a mandatory `option`, ran it without, and got the following output :

```
error: missing required argument &#39;name&#39;
```

Quote `'` characters were displayed as HTML entity instead of UTF8.

Thanks

**Comment by shadowspawn** [comment]
This is not due to Commander itself. By default, the error is displayed using code like:

```
process.stderr.write(`error: missing required argument '${name}'`)
```

Your program can change the way errors are displayed using `.configureOutput()`, and supplying a custom `writeErr` or `outputError`.

What are you using to run the program? (node?) What terminal are you running the command in?

**Comment by KaKi87** [comment]
Mea culpa, [`i18next`'s default configuration](https://www.i18next.com/translation-function/interpolation#unescape) was the problem.

Sorry for the inconvenience.
