### ISSUE TITLE
Async action not executed fully

### ISSUE THREAD

**Issue by Firgeis** [tj/commander.js#1898]
The following code results in the action stopping in the second await:

```
program.command('action')
  .action(async () => {
    await Promise.resolve();
    console.log("1")
    await new Promise(() => setTimeout(() => {}, 1));
    console.log("2")
  });

program.parseAsync().then(() => {});
```

**Comment by shadowspawn** [comment]
Thanks for the example, and then the simplified example. I'll have a look into it.

**Comment by shadowspawn** [comment]
It might be a problem with your async and promises. I modified the `setTimeout` line and tried this:

```js
const { program } = require('commander')

program.command('action')
  .action(async () => {
    console.log("0")
    await Promise.resolve();
    console.log("1")
    await new Promise(resolve => setTimeout(resolve, 1000, 'dummy'));
    console.log("2")
  });

console.log("before parseAsync")
program.parseAsync().then(() => {});
console.log("after parseAsync")
```

And with node 18 see:
```
% node index.js action
before parseAsync
0
after parseAsync
1
2
```

**Comment by Firgeis** [comment]
Trying to understand that is wrong here, they seem to run fine on their own. Also if they have an issue, is it possible to display it in any way? Why did the line below needed to be changed?
```
await new Promise(() => setTimeout(() => {}, 1));
```

**Comment by shadowspawn** [comment]
It is a valid timer. But the code following the await call is never being called.

The `Promise` and `await` implementation require some help from the author. What `await` effectively does is wrap the following code up into a callback to call later. What `setTimeout` does is call a function later. You have a timeout, but are not calling the resolve callback from the Promise so the code after the await line never gets run.

I find it a bit magical, but _much_ better than writing nested callbacks by hand! `setTimeout` is commonly used in examples since it is easy to understand that code is running later: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#

**Comment by shadowspawn** [comment]
> Also if they have an issue, is it possible to display it in any way?

By Commander? No, there is nothing for Commander to detect. You can take Commander out of the example and see the same behaviours.

```js
async function action() {
    console.log("0")
    await Promise.resolve();
    console.log("1")
    await new Promise(resolve => setTimeout(resolve, 1000, 'dummy'));
    console.log("2")
};

console.log("before action call")
action().then(() => {});
console.log("after action call")
```

**Comment by shadowspawn** [comment]
> Why did the line below needed to be changed, seems like a valid timer to me?

Just focusing on that line, this might help make it clearer. The Promise passes a callback which you are ignoring.

```js
await new Promise((codeToCallWhenPromiseResolves) => setTimeout(() => {}, 1));
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
