### ISSUE TITLE
passThroughOptions is not working as expected

### ISSUE THREAD

**Issue by ArtemSadikov** [tj/commander.js#1911]
There's in-buit feature which is called 'passThroughOptions'.

In examples, only thing we need to pass options from parent to sub command is to do something like this

```javascript
const cmd = program
    .command('main')
    .enablePositionalOptions()
    .option('-t', 'type', 'apple')
    
cmd
    .command('sub')
    .passThroughOptions()
    .action((options) => {
        console.log(options); // expected object '{ type: 'apple' }'
    });
``` 

so, if I run program like this, I only get empty result in options argument (```{}```)

what is wrong with code?

**Comment by shadowspawn** [comment]
`passThroughOptions()` is to stop the option processing so the trailing options can be passing through to another program, using spawn say.

For seeing the options defined higher up in the command chain, see `.optsWithGlobals()`.

If you would like a reworked example from your code, what are you typing on the command line? (It looks like you might have wanted `.name('main')` rather than `.command('main')`.)

**Comment by ArtemSadikov** [comment]
> `passThroughOptions()` is to stop the option processing so the trailing options can be passing through to another program, using spawn say.
> 
> For seeing the options defined higher up in the command chain, see `.optsWithGlobals()`.
> 
> If you would like a reworked example from your code, what are you typing on the command line? (It looks like you might have wanted `.name('main')` rather than `.command('main')`.)

thanks for provided solution, that works! I was typing like 

```bash
cli main -t apple sub
```

and expected that option type will be in sub command options, but it wasn't.

I'll resolve this, better reading docs next time...
