### ISSUE TITLE
Make auto help optional

### ISSUE THREAD

**Issue by ajcrites** [tj/commander.js#242]
There may be some circumstances where `--help` or `-h` should perform their `.on("--help")` duties, but we may not want to print out the automatic help message.

`.help` is already a method, so I propose a method like `.helpFlags` that you could include in the usual parse chain that would take overriding help flags as an argument.  `--help` and `-h` would still work by default, but you could do `.helpFlags("-a, --ayudar")` to use those instead or even `.helpFlags()` to prevent anything from outputting the help automatically.

**Comment by shadowspawn** [comment]
Not currently planning a plugin system, but keeping this bug open for now as an early request for being able to override automatic help behaviour.

**Comment by shadowspawn** [comment]
There is not currently a way to disable the auto-help, but from v3 there is `.helpOption` to customise the help flags and message.
https://github.com/tj/commander.js/releases/tag/v3.0.0

This issue has not had any activity in years. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by RonWang** [comment]
Still need this feature in great demand, as we want to add ASCii art for our CLI name at the front of the help message, and correct some help message auto-generated but not useful for our case. Appending on '--help' event won't help. Isn't this not supported in the short term?

**Comment by shadowspawn** [comment]
Commander v6.1 allows allows disabling the built-in help option: #1325
