### ISSUE TITLE
Option values with dashes "-" in them cause issues

### ISSUE THREAD

**Issue by henrytseng** [tj/commander.js#250]
We have a cli command used for geo coordinates look up.  

```
 $ lookup -g -83,23
```

Should look up geo coordinates at -83 lat and 23 longitude but it looks like it's being parsed as an option -8 instead.  Even using quotes does not seem to work.  

```
 $ lookup -g "-83,23"
```

Where we're configuring program with 

```
 program.option('-g, --geocoords [coords]', 'Geo-coordinates to sort by nearest [coords]')
```

**Comment by shadowspawn** [comment]
Making the option have a required value is appropriate, and avoids the dash issue, as per https://github.com/tj/commander.js/issues/250#issuecomment-54650480

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
