### ISSUE TITLE
program.options

### ISSUE THREAD

**Issue by dvv** [tj/commander.js#29]
A hash of options values is welcome. Right now it's hard (if ever) to determine what in `program` object is option and what is internal helpers.
TIA,
--Vladimir

**Comment by trusktr** [comment]
If only v5.0.0 included a change to put all parsed options on a subobject. It's too late now.

Can we have this for v6?

**Comment by shadowspawn** [comment]
@trusktr 

The current support is:
- `.opts()` to return the options and values
- `storeOptionsAsProperties(false)` to stop storing properties directly on the Command object

I don't plan to add a public sub-object as well, partly because the `.opts()` function allows a smooth transition, and partly because the function already used the best name! 😄
