### ISSUE TITLE
How to use `Command.prototype.allowUnknownOption`?

### ISSUE THREAD

**Issue by rjsteinert** [tj/commander.js#354]
I must not be understanding how this library is put together, sorry. I'm trying something like..

```
var program = require('commander');
program.allowUnknownOption(true);
```

With that code above an exit is still happening but not if I set `this._allowUnknownOption = false;` to `this._allowUnknownOption = true;` on line 85.

**Comment by specious** [comment]
[In the tests](https://github.com/tj/commander.js/blob/93c53212255b9ebde3b7ed85fa6b4796dc76c9a6/test/test.command.allowUnknownOption.js#L36) I saw you can do:

```js
var app = require('commander');
app.allowUnknownOption();
```

It worked for me.

**Comment by thasmo** [comment]
This works well for me.
```js
var commander = require('commander');
commander.allowUnknownOption(true);
```

**Comment by shadowspawn** [comment]
Thanks for explanation @specious and @thasmo 

This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
