### ISSUE TITLE
spaces/apostrophes after options not working like other Linux CLI programs

### ISSUE THREAD

**Issue by gavinengel** [tj/commander.js#359]
There are various syntax of passing options that I jump back and forth between.  I've found that commander gets confused sometimes and it gives me pause.  I'd love if commander can handle all these scenarios:

```
foo-bar -u baz -p baz -n foo; # success
foo-bar -u 'baz' -p 'baz' -n 'foo'; # success
foo-bar -u "baz" -p "baz" -n "foo"; # success
foo-bar -u=baz -p=baz -n=foo; # fail
foo-bar -u='baz' -p='baz' -n='foo'; # fail
foo-bar -u="baz" -p="baz" -n="foo"; # fail
foo-bar -ubaz -pbaz -nfoo; # fail
```

**Comment by caspervonb** [comment]
:+1:

**Comment by shadowspawn** [comment]
Thanks for the examples.

This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
