### ISSUE TITLE
sub commands for multipurpose cli app

### ISSUE THREAD

**Issue by uptownhr** [tj/commander.js#454]
I'm working on a general cli app for our company and it'll be multipurpose for different areas of the infrastructure. The examples provide ways to separate out commands using git-style. But is there a way to have another branch of commands from the git-style? 

For example, i have one command called, `server` for example, and I want to define sub commands of server. I'm aware I can do this through flags but not seeing any examples of sub commands that can take it's own flags. 

Any help is appreciated!

**Comment by SomeKittens** [comment]
What would a typical use of `server` be?

Are you looking for sub-sub-commands, or multiple commands, each with its own subcommand?

**Comment by curioussavage** [comment]
@SomeKittens I am trying to do the same thing as @uptownhr I think.

I want a command `project`

and I want sub commands like so: `add` `list` `edit` that each take different args.

So usage would be something like `project add  "my project" --categories="foo,bar,baz"`

Not clear to me from docs what is the best way to do this with commander. The git like subcommands section says put sub command in its own file. Maybe a more complete example would help. Would I just export a function or can i export another commander program in order to be able to specify args?

**Comment by curioussavage** [comment]
For anyone else with a simliar question: the executable the docs mention for subcommands should be another commander program. Commands you define in it can have their own arguments defined. They will all get passed through, even if the command in the main program doesn't define them.

**Comment by shadowspawn** [comment]
Thanks for explanation @curioussavage 

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
