### ISSUE TITLE
Variadic arguments don't work properly with isDefault set to true

### ISSUE THREAD

**Issue by zweicoder** [tj/commander.js#539]
Using `$ service serve 1 2 3`,
This works

```
program
    .command('serve [files...]')
    .action(function (files){
         console.log(files) // [1, 2, 3]
    })
```

This doesn't

```
program
    .command('serve [files...]', {isDefault:true})
    .action(function (files){
         console.log(files) // 1
    })
```

Edit: 
Seems like it's not the `inDefault` setting in particular that has a problem. There are other cases where it fails as well:

```
program.version('1.0.0')
    .usage('[files...]')
    .action((files) => {
        console.log(files) // 1
    })
```

**Comment by shadowspawn** [comment]
I was not able to reproduce this issue, but the command options are the third parameter, so expected call would be like:

```
    .command('serve [files...]', undefined, {isDefault:true})
```

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
