### ISSUE TITLE
Coercion function gets called with incorrect value

### ISSUE THREAD

**Issue by electerious** [tj/commander.js#551]
**Command**

```sh
rosid compile src/ dist/ -i **/_* -i **/.bower.json -i **/assets/includes
```

**Code**

```js
const collect = function(value, list) {

	console.log(value)

}

program
	.command('compile <srcPath> <distPath>')
	.option('-i, --ignore <filePath>', 'exclude files from the copy-task', collect, [])
	.action((srcPath, distPath, opts) => {

		// ...

	})
```

**Output**

```
**/_*
**/.bower.json
dist/assets/includes
```

The first two values are correct, but the last one is a mix between `<distPath>` and `**/assets/includes`.

**Expected output**

```
**/_*
**/.bower.json
**/assets/includes
```

**Versions**

node v6.2.0
npm  v3.10.2
commander.js v2.9.0

**Comment by electerious** [comment]
Same happens in minimist (https://github.com/substack/minimist/issues/97). Is using `**` valid at all?

**Comment by leo** [comment]
@electerious Maybe escaping them as a string works?

```bash
rosid -i "**/.bower.json"
```

**Comment by electerious** [comment]
Escaping them as strings works. Good workaround, but I still wonder what's causing the issue.

**Comment by leo** [comment]
@electerious The output is inconsistent because minimist/commander never actually receive all of the strings if you don't escape it as such. Instead of that, bash simply tries to format the paths by itself and then makes the parsed strings available within the process.

[Here](http://unix.stackexchange.com/a/85580)'s an example. As the guy is stating it: It's neither a bug in minimist or commander, nor in bash. It's just a side-effect of trying to do some low-level logic where it's not really needed.

**Comment by electerious** [comment]
Thanks for letting me know @leo! That helps a lot.
