### ISSUE TITLE
Option to prefix help with text

### ISSUE THREAD

**Issue by jez9999** [tj/commander.js#578]
Hi,

I would like an option to prefix the --help output with my program's banner along the top, eg.

```
=====
MyProgram version 1.2.3
=====

  Usage: myprogram [options]
  ... etc...
```

There doesn't seem to be a way to do this right now (at least not just for when the help text gets displayed) - could it be added?

**Comment by b4dnewz** [comment]
this will be a super feature, so you can prefix your command line tools with (for example) ASCII art like the most of cli tools out there.

**Comment by kodie** [comment]
Crazy that this hasn't been implemented yet

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest. 

This request did get some 👍 so I appreciate there may be some interest. We already have a few help customisation options, but not something that does a "header". 
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
This came up again, and I have an idea for a possible implementation:
https://github.com/tj/commander.js/issues/1023#issuecomment-574451728
