### ISSUE TITLE
Format help descriptions that are too long

### ISSUE THREAD

**Issue by jez9999** [tj/commander.js#579]
When a param description is too long, it will simply spill over to the next line in the console which looks very ugly.  Commander.js should format this properly by detecting console width, doing line breaks where appropriate, as well as indenting to the correct level.

**Comment by shadowspawn** [comment]
This is also reported in more recent https://github.com/tj/commander.js/issues/759

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
