### ISSUE TITLE
program.opts() can be overridden by an option

### ISSUE THREAD

**Issue by rijnhard** [tj/commander.js#584]
``` javascript
import program from 'commander';

program.getOptions = program.opts;
console.log('program.opts before', program.opts); // prints body of opts() function

program.option('--opts <path>', 'specify opts path', 'test/mocha.opts');
program.parse(process.argv);

console.log('program.opts after', program.opts); // prints test/mocha.opts
console.log('program.opts()', program.opts()); // errors, is not a function
console.log('program.opts().opts', program.getOptions().opts); // this is the workaround that works.
```

Shouldnt the function be protected from being overridden? 
it's easy enough to use `program.opts().opts` to get any properties that would override default functions.

But in cases (like in the mocha code) where they are using the overridden property `program.opts` it will introduce errors. 

Thus it is a breaking change. but none the less the workaround introduce more problems with reuse then anything else.

**Comment by shadowspawn** [comment]
I have referenced this issue as one of a number of related issues.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
