### ISSUE TITLE
main options intertwine with command options

### ISSUE THREAD

**Issue by joelharkes** [tj/commander.js#598]
for example have the following setup

```javascript
program
    .option('-v --verbose', 'show verbose logging')
program
    .command('release')
    .option('-v --version <version>', 'version of the release')
```

if I execute my command with

```
myBin release -v 1.0.0
```

then program.verbose  = true, although i expect it to be false.

i expect it to be true when: `myBin -v release` (see difference in order).

**Comment by shadowspawn** [comment]
The global options can come before or after the command, so there is a conflict between the two uses of -v.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Pull Request opened to add `.enablePositionalOptions()` and `.passThroughOptions()`: #1427
