### ISSUE TITLE
wrong version is outputted in help

### ISSUE THREAD

**Issue by sandrodz** [tj/commander.js#624]
--version outputs, it seems babel version?

Strange, shouldn't it be 1.0.1 like defined in program.version() ?

<img width="395" alt="screen shot 2017-04-30 at 5 16 09 pm" src="https://cloud.githubusercontent.com/assets/8479569/25564642/bb9722ce-2dc8-11e7-8891-323eafa2c291.png">
<img width="459" alt="screen shot 2017-04-30 at 5 16 12 pm" src="https://cloud.githubusercontent.com/assets/8479569/25564643/bb983e0c-2dc8-11e7-9fe6-7ce02dcc608a.png">

**Comment by mrozbarry** [comment]
Not sure if this is related, but in my package.json, I have `babel-cli`, `babel-preset-es2017`, and `babel-register`, all of which are pegged at `6.24.1`. I see you're running with babel-node/cli as well, so maybe commander is using that for some reason?

**Comment by abetomo** [comment]
@mrozbarry Thank you.

@sandrodz 
Apparently `--version` is not an option of `ripple`, it seems that it is treated as being an option of `bable-node`.
(`commander.js` is also used in babel-node.)

**Comment by shadowspawn** [comment]
This was probably due to using global commander object and there is now a work-around, see for example #790.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
