### ISSUE TITLE
Command.opts() values are always undefined

### ISSUE THREAD

**Issue by carragom** [tj/commander.js#626]
Hi there,

Got an issue with the opts() method. According to the [docs](http://tj.github.io/commander.js/#Command.prototype.opts) it should return an Object with option names as keys. But the values always seem to be undefined. From what I can see, these values get loaded [here](https://github.com/tj/commander.js/blob/master/index.js#L752) but I don't really see how `this[key]` could ever return anything other than `undefined`. Am I missing something here?

**Comment by carragom** [comment]
Further checking, this seems to be related to default value assignment. These values get set [here](https://github.com/tj/commander.js/blob/master/index.js#L381) which according to the comment explicitly set boolean flags only when negated by `--no-*`. I guess the question then is, how to set a default value for a boolean flag that is not negated with `--no-*`.

**Comment by shadowspawn** [comment]
I have this noted as an example of issues with how "boolean" options are handled.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
