### ISSUE TITLE
Fatal error when there are 2 or multiple same alias being used

### ISSUE THREAD

**Issue by leeadrian841** [tj/commander.js#640]
I come across this error when I used 2 same alias being used.
There is no notification telling the same alias that has been used multiple times and it may be hard to debug the error.

<img width="1413" alt="screen shot 2017-06-14 at 4 32 55 pm" src="https://user-images.githubusercontent.com/20371239/27269189-4fe0f136-54e7-11e7-9159-146b18936c7e.png">

**Comment by shadowspawn** [comment]
Having a warning in this case is a reasonable suggestion, thanks.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
