### ISSUE TITLE
Options object is not strictly the user input

### ISSUE THREAD

**Issue by elliot-nelson** [tj/commander.js#644]
Take this simple program:

```
program
    .command('list')
    .description('lists all objects')
    .options('--name <name>', 'filter by name')
    .action(function (options) {
        // Program prints "filter enabled", even if user does not provide a value.
        console.log(options.name ? 'filter enabled' : 'filter disabled');
    })
```

The `options` object is not a raw property bag of the command line options, it is an object with some functions defined on it, one of which seems to be `name`, another is `parent`.

I feel like the API should be changed so there aren't hidden mines under certain option names -- or, at least, the documentation should make it clear what option names will conflict with these special API functions.

**Comment by shadowspawn** [comment]
This is an area we want to improve, and will be a breaking change. I have referenced this issue as one of a number of related issues.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
I have opened a Pull Request which allows storing option values separately rather than as command properties (access using `.opts()`), and passes the options (rather than the command) to the action handler. Opt-in using

```
program.configureCommand({ modern: true });
```

See #1102
