### ISSUE TITLE
Default command shouldn't show in help menu

### ISSUE THREAD

**Issue by grant** [tj/commander.js#705]
The default command (*) shows in an unhelpful command:

```js
program
  .command('*', { isDefault: true })
  .action((command) => {
    // ...
  });
```

Results in help output like this:

```
  Commands:

    login                                            Log in
    logout                                           Log out
    *                                                [object Object]
```

The last line should be hidden from the help output. Or adding a description should work.

**Comment by a-fas** [comment]
Try adding `{ noHelp: true }` - it should hide the command
```
.command('*', { hoNelp: true })
```

**Comment by wramp** [comment]
@a-fas 

i guess you mean

.command('*', { noHelp: true })

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Side notes:
- I was not able to reproduce the `[object Object]` behaviour
- the `isDefault` currently only works for executable commands, not action based handlers

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
