### ISSUE TITLE
How to get option list?

### ISSUE THREAD

**Issue by w96k** [tj/commander.js#712]
Is there any way to get just an array of used options (flags)?

**Comment by tomorrowthief** [comment]
+1

**Comment by olivierbossel** [comment]
+1

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

There is a `.opts()` routine which returns an object with the options and their values. If that doesn't suit your use case, would you please give some context about what you want it for.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
