### ISSUE TITLE
Git style commands and different than module name bin command issue

### ISSUE THREAD

**Issue by jarrodek** [tj/commander.js#714]
I have the following setup:

NPM module name: `api-console-cli`
Registered in package.json command: `api-console`

```
  "bin": {
    "api-console": "bin/api-console-cli.js"
  }
```
and the following error when trying to run the program on Windows:

```
C:\workspace\api-console-cli>api-console dev --help
module.js:491
    throw err;
    ^

Error: Cannot find module 'C:\workspace\api-console-cli\api-console-cli-dev'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
```

Under Linux and Mac it works when the sub-command file is located in `./bin/api-console-dev.js`. Windows throws an error which can be fixed by creating the `./bin/api-console-cli-dev.js`. This file contains a `require` of the original file.

Apparently on windows commander ignores that the actual CLI command is different than the npm module name. It should request one file only on all platforms.

You can find the source code here: https://github.com/mulesoft-labs/api-console-cli

**Comment by patrickmcelwee** [comment]
I ran into this on Windows 7 as well, but my package.json looks like this:

```javascript
  "main": "index.js",
  "bin": {
    "muir": "./index.js"
  }
```

and the error when running `muir new`, for example, is looking for a file named `index-new`. If I run `muir demo`, it looks for `demo-new`

**Comment by shadowspawn** [comment]
Pull Request being considered for v3 is #999, which will at least allow manual override.

**Comment by shadowspawn** [comment]
This issue will at least have a work-around when v3.0.0 is released. Available now as a prerelease. See #1001

**Comment by shadowspawn** [comment]
.command now supports the executableFile option (thanks to @abetomo).
Shipped in v3: https://github.com/tj/commander.js/releases/tag/v3.0.0

**Comment by shadowspawn** [comment]
The issue is Commander is using the script from the command line (i.e. `process.argv[1]`) to find the base name. This leads to a range of behaviours.

On Mac `process.argv[1]` when using:
- `node bin/api-console-cli.js` has full path of local `bin/api-console-cli.js`
- `api-console` has full path of installed command symlink `api-console `

On Windows `my-cli` is a cmd and not a symlink so `process.argv[1]` when using:
- `node bin/api-console-cli.js` has full path of local `bin/api-console-cli.js`
- `api-console ` has full path of installed `bin/api-console-cli.js`

A slightly fragile but backwards compatible behaviour might be to look for both variations on Mac, so that `bin/api-console-cli.js` would be found whether launched directly using node or through the command, on Mac and Windows.

**Comment by shadowspawn** [comment]
Previous issue and associated PR: #826 #830

Issue covering multiple causes but some related comments: #786 
- https://github.com/tj/commander.js/issues/786#issuecomment-416186134
- https://github.com/tj/commander.js/issues/786#issuecomment-435574390

**Comment by shadowspawn** [comment]
PR to resolve this issue: #1571

**Comment by shadowspawn** [comment]
Commander v9 has been released.
