### ISSUE TITLE
Specifying command description forces lookup of command in separate file

### ISSUE THREAD

**Issue by maximilianschmitt** [tj/commander.js#715]
```
Commander 2.11.0
Node 6.11.0
```

Simple test case:

```javascript
'use strict'

const app = require('commander')

app
  .command("command-name", "asdasd") // <-- Note the added description
  .action(function() {
    console.log("Executing command-name");
  });

app.parse(process.argv)
```

Output (exit code 1):

```
$ node app.js command-name
Executing command-name

  app-command-name(1) does not exist, try --help
```

Expected output (exit code 0):

```
$ node app.js command-name
Executing command-name
```

Removing the description in `.command()` yields the expected results:

```javascript
'use strict'

const app = require('commander')

app
  .command("command-name")  // <-- Note the missing description
  .action(function() {
    console.log("Executing command-name");
  });

app.parse(process.argv)
```

**Comment by shadowspawn** [comment]
I agree, we should improve the documentation and the runtime behaviour to make this clearer. I have referenced this issue as one of a number of related issues.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
