### ISSUE TITLE
Make it clear that you can't pipe action to command that was invoked with description

### ISSUE THREAD

**Issue by imam** [tj/commander.js#776]
> When .command() is invoked with a description argument, no .action(callback) should be called to handle sub-commands, otherwise there will be an error. This tells commander that you're going to use separate executables for sub-commands, much like git(1) and other popular tools.

Can we make the error clearer, if anyone wants to pipe `action` on `command` with a description argument, we should provide clarity that it isn't allowed by throwing an error, and refer to above statement? This error just occurred to me, and I would love to experience the error without the confusion about what was really happening.

**Comment by shadowspawn** [comment]
I agree, we should improve the documentation and the runtime behaviour to make this clearer. I have referenced this issue as one of a number of related issues.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
