### ISSUE TITLE
Git-style subcommands not working if files are implicit '.js' but command is ran without '.js'

### ISSUE THREAD

**Issue by auderer** [tj/commander.js#785]
If your command files use the `.js` extension, but you run the command via `node mycommand` instead of `node mycommand.js`, any git-style sub-commands will fail in `Command.prototype#executeSubCommand`

This failure is on line 531, column 15 of `index.js`:
```js
var f = argv[1];

// ...

link = fs.lstatSync(f).isSymbolicLink() ? fs.readlinkSync(f) : f;
```

Specifically this part is failing:
```js
fs.lstatSync(f)
```

This is causing an error because Commander is looking for the file that corresponds to argv[1], so in this specific case, argv[1] doesn't match the actual file name.

**Comment by shadowspawn** [comment]
Reproduced the problem, but there is an easy work-around to specify the full filename.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by auderer** [comment]
@shadowspawn I'm willing to work on a PR for this if you re-open and assign to me. It shouldn't be difficult to fix.

**Comment by shadowspawn** [comment]
Done. Thanks.

**Comment by shadowspawn** [comment]
Inactive for a few months. Closing again.

This issue matches the wording of the title in #512, but is a much more specific case. Also has some similarities with #1044.
