### ISSUE TITLE
how to identify -a and -ab on options?

### ISSUE THREAD

**Issue by Vuchan** [tj/commander.js#796]
## Code:
```javascript
#!/usr/bin/env node
const program = require('commander');

program
  .version('0.0.1')
  .arguments('[options]')
  .description('Use xx For xx')
  .usage('<type>')
	.option('-a, --anythings')
	.option('-ab, --abthings')
	.action(function(options) {
		console.log(options)
	})
	.parse(process.argv)

if (!program.args.length) {
  program.help()
};
```

## Run 1
```bash
#bash
node test.js -a 'a'   // it works well
```

## Run 2
```bash
#bash
node test.js -ab 'abc' // error: unknown option `-b'
```

+ Is this wrong? 
+ if it is how to fix that?
+ if not can u tell me why or where is the code about that??

3ks

**Comment by JohnRGee** [comment]
You can use a letter option with one dash like `-a`, or a word option with two dashes like `--anything`, or one of each like you did with `option('-a, --anythings')`.

The problem is that `-ab` is not a valid combination as a single dash and a word.

On the command-line when you type multiple options (letters) after a single dash, it is treated the same as using the options separately, so
`-ab` == `-a -b`
which is how you get the (initially surprising) error `error: unknown option -b`

(You might have seen the multiple option pattern with commands like `ls -al`.)

**Comment by Vuchan** [comment]
Thanks in advance, your answer let me know where i made wrong, and how to fixes it next.
