### ISSUE TITLE
sub command option callback error

### ISSUE THREAD

**Issue by xujif** [tj/commander.js#860]
talk is cheap  
```typescript
program.option('--vv', 'verbose', () => {
    console.log('enable program verbose')
})

program.command('rm <dir>')
    .option('-r, --recursive', 'Remove recursively')
    .option('--vv', 'verbose', () => {
        console.log('enable sub verbose')
    })
    .action(function (dir, cmd) {
        console.log('remove ' + dir + (cmd.recursive ? ' recursively' : ''))
    })

program.parse(process.argv)
```
with next executions:
```bash
# node dist\index rm dist --vv
enable program verbose                  *** shuold be enable sub verbose ***
remove dist

# node dist\index rm --vv dist
enable program verbose
remove dist

```

**Comment by xujif** [comment]
the sub commond option callback never be called when has same option name with program.

**Comment by shadowspawn** [comment]
Commander does not treat program options as positional, they apply before and after commands. (There are unfortunately not warnings for overlapping options.)

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
