### ISSUE TITLE
What about having a CLI to bootstrap commander based apps

### ISSUE THREAD

**Issue by open-source-explorer** [tj/commander.js#920]
I would suggest having some sort of `create-cli-app` just as the way we have `create-react-app`, `vue-cli` etc. It seems to be really useful, especially for beginners :thinking:

**Comment by viniciusls** [comment]
Hi! But what do you think it would be good to implement inside this bootstrap? Because in the examples that you mentioned, we have complex folder structures and configs to create and manage while in commander I just see a 'bin' which will be responsible for calling your own background logic. Do you have some example of complex application?

I started using commander.js recently and I'm liking so much of it and I'm looking for ideas which I can help implement.

**Comment by shadowspawn** [comment]
I think a simple commander program is so simple that not much benefit from a create application. Thanks for the suggestion though.

Thank you  for your contributions.

**Comment by shadowspawn** [comment]
One package I see mentioned a lot which has bootstrap assistance as a key feature is: https://oclif.io
